#pragma once
#include "common.hpp"
#include "utility/scanner.hpp"
#include "utility/printer.hpp"
#include "utility/md_vec.hpp"
#include "utility/bin_search.hpp"
#include "utility/clamp_op.hpp"
#include "utility/modint.hpp"
#include "graph/graph.hpp"
